# Generated by Django 3.0.3 on 2020-11-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Munition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kanon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanon_name', models.CharField(max_length=200)),
                ('munition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanon.Munition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanon.User')),
            ],
        ),
    ]
