# Generated by Django 3.1.3 on 2020-11-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='munition',
            name='munition_type',
            field=models.CharField(default='New Amuniton Type', max_length=50),
            preserve_default=False,
        ),
    ]
